// Decompiled with JetBrains decompiler
// Type: SubFormation
// Assembly: ProEra.Game, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: A251AB60-A6EC-4F45-B61A-221E02FF094C
// Assembly location: C:\Users\nicke\Desktop\Folders\pro era modding again lol\pcversion\NFL Pro Era\NFL PRO ERA_Data\Managed\ProEra.Game.dll

public enum SubFormation
{
  None,
  Normal,
  Slot_Flex,
  Tight,
  Twin_TE,
  Twins,
  Y_Trips,
  Trips,
  Spread_5WR,
  Bunch_5WR,
  Normal_Y_Flex,
  Quads_Trio,
  Slot_Offset,
  Split_Offset,
  Trey,
  NormalDimeDropping,
  TightWideBack,
  Trey_Open,
  Flex_Trips,
  Heavy,
  Twins_Over,
  Ace,
  Bunch,
  Slot,
  Spread_Flex,
  Trio,
  Big,
  Spread,
  Big_Twins,
  Trio_4WR,
  Wing_Trio_TE,
  Close,
  Twins_Flex,
  Close_Twins,
  Field_Goal,
  Punt,
  Kickoff,
  Onside_Kick,
  Field_Goal_Block,
  Punt_Return,
  Kick_Return,
  Onside_Kick_Return,
  Two_Four,
}
